/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loja;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 * 
 * Todos os comentários não originais do NetBeans do código foram feitos por mim
 * com o intuito de facilitar o entendimento do código e agilizar a apresentação
 * 
 * Decidimos simular um sistema de cadastro e compra de produtos do cliente
 * como vemos no dia a dia em lojas iguais a Amazon.
 */
public class LojaApp extends javax.swing.JFrame {
    
    private List<Cliente> cliente;
    private Iterator it;
    private List<Produto> estoque;
    private int indice;

    /**
     * Creates new form LojaApp
     */
    public LojaApp() {
        initComponents();
        cliente = new ArrayList();
        it = cliente.iterator();
        estoque = new ArrayList();
        
        // Estoque predefinido
        estoque.add(new Produto("Console", "PS5", 10));
        estoque.add(new Produto("Console","Xbox", 10));
        estoque.add(new Produto("Celular","Samsung", 10));
        estoque.add(new Produto("Celular","iPhone", 10));
        estoque.add(new Produto("Video Game","Alan Wake", 10));
        estoque.add(new Produto("Video Game","Call of Duty", 10));
        estoque.add(new Produto("Acessórios","Mouse Gamer", 10));
        estoque.add(new Produto("Acessórios","Teclado Gamer", 10));
          
        metodoComboBoxes();

    } 
        
    public LojaApp(List cliente){
        initComponents();
        this.cliente = cliente;
        it = this.cliente.iterator();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNomeLabel = new javax.swing.JLabel();
        jEnderecoLabel = new javax.swing.JLabel();
        jCpfLabel = new javax.swing.JLabel();
        jEmailLabel = new javax.swing.JLabel();
        jNomeText = new javax.swing.JTextField();
        jCPFText = new javax.swing.JTextField();
        jEmailText = new javax.swing.JTextField();
        jEnderecoText = new javax.swing.JTextField();
        jTipoLabel = new javax.swing.JLabel();
        jTipoBox = new javax.swing.JComboBox<>();
        jNomeProdutoLabel = new javax.swing.JLabel();
        jNomeBox = new javax.swing.JComboBox<>();
        jFinalizaButton = new javax.swing.JButton();
        jLimpaTelaButton = new javax.swing.JButton();
        jCriarContaButton = new javax.swing.JButton();
        jExcluirContaButton = new javax.swing.JButton();
        jComprarButton = new javax.swing.JButton();
        jVoltarButton = new javax.swing.JButton();
        jAlterarUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO E COMPRA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("- LOJA DE PRODUTOS ELETRÔNICOS -");

        jNomeLabel.setText("Nome :");

        jEnderecoLabel.setText("Endereço :");

        jCpfLabel.setText("CPF :");

        jEmailLabel.setText("E-Mail :");

        jTipoLabel.setText("Selecione o tipo do produto :");

        jTipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Console", "Celular", "Video Game", "Acessórios" }));
        jTipoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoBoxActionPerformed(evt);
            }
        });

        jNomeProdutoLabel.setText("Selecione o produto :");

        jNomeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeBoxActionPerformed(evt);
            }
        });

        jFinalizaButton.setText("Finalizar");
        jFinalizaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinalizaButtonActionPerformed(evt);
            }
        });

        jLimpaTelaButton.setText("Limpar Tela");
        jLimpaTelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpaTelaButtonActionPerformed(evt);
            }
        });

        jCriarContaButton.setText("Criar Conta");
        jCriarContaButton.setToolTipText("");
        jCriarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriarContaButtonActionPerformed(evt);
            }
        });

        jExcluirContaButton.setText("Excluir Conta");
        jExcluirContaButton.setToolTipText("");
        jExcluirContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirContaButtonActionPerformed(evt);
            }
        });

        jComprarButton.setText("Comprar");
        jComprarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComprarButtonActionPerformed(evt);
            }
        });

        jVoltarButton.setText("Voltar");
        jVoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarButtonActionPerformed(evt);
            }
        });

        jAlterarUsuario.setText("Alterar Conta");
        jAlterarUsuario.setToolTipText("");
        jAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLimpaTelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jExcluirContaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCriarContaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFinalizaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComprarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jVoltarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jEnderecoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEnderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jTipoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jNomeProdutoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNomeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmailText))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jCpfLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCPFText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNomeText)))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCpfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEmailLabel)
                    .addComponent(jEmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEnderecoLabel)
                    .addComponent(jEnderecoText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoLabel)
                    .addComponent(jTipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeProdutoLabel)
                    .addComponent(jNomeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jCriarContaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jExcluirContaButton)
                    .addComponent(jComprarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoltarButton)
                    .addComponent(jAlterarUsuario))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFinalizaButton)
                    .addComponent(jLimpaTelaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFinalizaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinalizaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jFinalizaButtonActionPerformed
    // Limpa a tela do usuario
    private void jLimpaTelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpaTelaButtonActionPerformed
        // TODO add your handling code here:
        limpar_tela();
    }//GEN-LAST:event_jLimpaTelaButtonActionPerformed
    // Cria a conta do usuario
    private void jCriarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriarContaButtonActionPerformed
        // TODO add your handling code here:
        String nome=jNomeText.getText();
        String cpf=jCPFText.getText();
        String email=jEmailText.getText();
        String endereco=jEnderecoText.getText();
        criar(nome,cpf,email,endereco);
        
        limpar_tela();
        
    }//GEN-LAST:event_jCriarContaButtonActionPerformed
    //ferramenta para excluir a conta
    private void jExcluirContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirContaButtonActionPerformed
        // TODO add your handling code here:
            if(JOptionPane.showConfirmDialog(null, "Você realmente deseja excluir a conta?","Processo de Exclusão",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==0)
            excluir();
    }//GEN-LAST:event_jExcluirContaButtonActionPerformed

    private void jComprarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComprarButtonActionPerformed
        // TODO add your handling code here:
        if (jNomeBox.getSelectedItem() != null) {
            String nomeProdutoSelecionado = (String) jNomeBox.getSelectedItem();
            Produto produtoSelecionado = estoque.stream().filter(p -> p.getNome().equals(nomeProdutoSelecionado)).findFirst().orElse(null);
            // Neste if criei um sistema para descontar do estoque e atualiza
            if (produtoSelecionado != null && produtoSelecionado.getEstoque() > 0) {
                produtoSelecionado.setEstoque(produtoSelecionado.getEstoque() - 1);
                
                // O programa tambem oferece a opção de voltar para a tela inicial do usuario que realizou a compra
                int resposta = JOptionPane.showConfirmDialog(null, "Compra efetuada com sucesso! Deseja retornr para a tela inicial?",
                        "Compra confirmada.", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    salvar_tela((Cliente) it.next());
                }
                // Caso o produto não possua mais estoque ou não foi escolhido, essas mensagens vão aparecer
            } else {
                JOptionPane.showMessageDialog(null, "Produto fora de estoque.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado.");
    }
    
    }//GEN-LAST:event_jComprarButtonActionPerformed
    // Bota de voltar a tela anterior
    private void jVoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarButtonActionPerformed
        // TODO add your handling code here:
        salvar_tela((Cliente) it.next());
    }//GEN-LAST:event_jVoltarButtonActionPerformed
    //altera os usuarios cadastrados
    private void jAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        if(!it.hasNext()){
            it=cliente.iterator();
            indice=0;
        }
        
        salvar_tela((Cliente) it.next());
        indice++;
    }//GEN-LAST:event_jAlterarUsuarioActionPerformed
    // Atualiza a ComboBox de Produtos baseado no tipo selecionado
    private void jNomeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeBoxActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jNomeBoxActionPerformed

    private void jTipoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoBoxActionPerformed
        // TODO add your handling code here:
        atualizaComboBox((String) jTipoBox.getSelectedItem());
    }//GEN-LAST:event_jTipoBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LojaApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlterarUsuario;
    private javax.swing.JTextField jCPFText;
    private javax.swing.JButton jComprarButton;
    private javax.swing.JLabel jCpfLabel;
    private javax.swing.JButton jCriarContaButton;
    private javax.swing.JLabel jEmailLabel;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jEnderecoLabel;
    private javax.swing.JTextField jEnderecoText;
    private javax.swing.JButton jExcluirContaButton;
    private javax.swing.JButton jFinalizaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLimpaTelaButton;
    private javax.swing.JComboBox<String> jNomeBox;
    private javax.swing.JLabel jNomeLabel;
    private javax.swing.JLabel jNomeProdutoLabel;
    private javax.swing.JTextField jNomeText;
    private javax.swing.JComboBox<String> jTipoBox;
    private javax.swing.JLabel jTipoLabel;
    private javax.swing.JButton jVoltarButton;
    // End of variables declaration//GEN-END:variables
    
    // Sistema para criar a conta
    private void criar(String nome, String cpf, String email, String endereco){
    
    Cliente criaCliente;
    criaCliente = new Cliente(nome,cpf,email,endereco);
    cliente.add(criaCliente);
    
    it=cliente.iterator();
    indice=0;
    
    }
    
    // Sistema de Excluir a Conta
    private void excluir(){
        
        it.remove();
        it=cliente.iterator();
        limpar_tela();
        
    }
    /*Sistema de Alterar
    * Nao Acabado
    private void alterar(int ponto){
        Cliente criaCliente;
        String nome=jNomeText.getText();
        String cpf=jCPFText.getText();
        String email=jEmailText.getText();
        String endereco=jEnderecoText.getText();
        
        criaCliente = new Cliente(nome,cpf,email,endereco);
        cliente.set(ponto, criaCliente);
          
    }
    */
    // Sistema de Limpar a Tela
    
    private void limpar_tela(){

    jNomeText.setText("");
    jCPFText.setText("");
    jEmailText.setText("");
    jEnderecoText.setText("");
    jTipoBox.setSelectedIndex(-1);
    jNomeBox.setSelectedIndex(-1);
    metodoComboBoxes();
    
    it=cliente.iterator();
    indice=0;
    
    }
    
    // Sistema de Salvar Tela
    
    private void salvar_tela(Cliente clienteSalvar){
        
    jNomeText.setText(clienteSalvar.getNome());
    jCPFText.setText(clienteSalvar.getCpf());
    jEmailText.setText(clienteSalvar.getEmail());
    jEnderecoText.setText(clienteSalvar.getEndereco());
    jTipoBox.setSelectedIndex(-1);
    jNomeBox.setSelectedIndex(-1);
    metodoComboBoxes();
    
    
    }
    
    /* Nesta parte criei um sistema para iniciar as duas Combo Boxes do programa
    *  A jNomeBox depende exclusivamente da escolha do usuario ao clicar na jTipoBox
    *  Por isso decidi criar este sistema
    */
    
    private void metodoComboBoxes() {
      
    jTipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Console", "Celular", "Video Game", "Acessórios"}));
    atualizaComboBox((String)jTipoBox.getSelectedItem());
    
    /* Parte muito importante do codigo
    *   Através de estudos online decidi implementar a função Listener
    *   Listener é basicamente um Ouvinte
    *   Ouvinte = Monitorar e Observar as ações e escolhas do usuário
    *   Auxiliando na filtragem a seguir.
    */
    jTipoBox.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTipoBoxActionPerformed(evt);
         }
      });
    }
    // Nesta parte criei uma forma de atualizar e filtrar os produtos do estoque
    // para mostrar tambem na tela

    private void atualizaComboBox(String tipoSelecionado) {
        List<String> produtosFiltragem = estoque.stream()
            .filter(produto -> produto.getTipo().equals(tipoSelecionado))
            .map(Produto::getNome)
            .collect(java.util.stream.Collectors.toList());
        jNomeBox.setModel(new javax.swing.DefaultComboBoxModel<>(produtosFiltragem.toArray(new String[0])));
    }

    // Mais uma forma de tratar, desta vez para mostrar as atualizacoes do estoque
    /*private void atualizarQuantidadeEstoqueText(String nomeProduto) {
        Produto produtoSelecionado = estoque.stream()
            .filter(p -> p.getNome().equals(nomeProduto))
            .findFirst()
            .orElse(null);

         if (produtoSelecionado != null) {
            jQuantidadeEstoqueText.setText(Integer.toString(produtoSelecionado.getEstoque()));
        } else {
            jQuantidadeEstoqueText.setText("");
        }
*/
}

    
    
    
